from . import inherit_product_product
from . import inherit_product_template
from . import inherit_purchse_order_line
from . import inherit_res_user
from . import inherit_sale_order
from . import inherit_sale_order_line
from . import mrp_tag
from . import product_category
from . import purchase_requisition
from . import res_partner
from . import stock_lot
from . import stock_move_line
from . import stock_picking
from . import stock_quant
from . import wizard_models
