from . import inherit_fiscal_position
from . import inherit_prodcut_temp
from . import inherit_product_temp_att_value
from . import inherit_sale_order
from . import inherit_sale_order_line
from . import inherit_stock_move
from . import ir_actions_report
from . import procurement_group
from . import product_oe_specification
from . import purchase_order
from . import sale_container_module
from . import stock_move_line
from . import stock_picking
from . import tires_conf
