# -*- coding: utf-8 -*-
{
    'name': 'Alamal Tires ',
    'version': '1.0',
    'summary': 'Alamal Tries customization',
    'description': 'Alamal Tries customization',
    'category': '',
    'author': 'Smartr Teknoloji',
    'depends': ['website_sale', 'sale_stock'],
    'data': [
        'data/partner_ledger.xml',
        'security/security.xml',
        'security/ir.model.access.csv',
        'wizard/print_reports_from_procurement_group_views.xml',
        'views/inherit_product_template_form_view.xml',
        'views/tires_conf.xml',
        'views/inherit_sale_order_form_view.xml',
        'views/inherit_fiscal_position_form.xml',
        'views/inherit_stock_picking.xml',
        'views/stock_by_sale_report.xml',
        'views/ir_actions_report_views.xml',
        'views/product_oe_specification_views.xml',
        'views/purchase_order_views.xml',
        'views/stock_move_line_views.xml',
        'report/template_report.xml',
        'report/report_picking_procurement_group.xml',
        'report/report_picking_procurement_group_demand.xml',
        'report/report_invoice_document.xml',
        'report/report.xml',
    ],
    'installable': True,
    'auto_install': False,
}
