from . import account_journal
from . import account_move
from . import inherit_product_product
from . import inherit_purchase_order
from . import inherit_res_partner
from . import procurement_group
from . import product_origin
from . import product_pricelist_item
from . import purchase_order_type
from . import res_company
from . import res_partner
from . import res_users
from . import sale_order
from . import stock_move
from . import stock_move_line
from . import stock_picking
